add_executable(train_transformer train_transformer.cpp)
target_link_libraries(train_transformer PRIVATE jasmine_headers)

add_executable(train_transformer_ce train_transformer_ce.cpp)
target_link_libraries(train_transformer_ce PRIVATE jasmine_headers)

add_executable(train_tf_base train_tf_base.cpp)
target_link_libraries(train_tf_base PRIVATE jasmine_headers)

add_executable(train_tf_kernel train_tf_kernel.cpp)
target_link_libraries(train_tf_kernel PRIVATE jasmine_headers)

add_executable(gpt2_generate gpt2_generate.cpp)
target_link_libraries(gpt2_generate PRIVATE jasmine_headers)

add_executable(gpt2_chat gpt2_chat.cpp)
target_link_libraries(gpt2_chat PRIVATE jasmine_headers)

add_executable(llama_chat llama_chat.cpp)
target_link_libraries(llama_chat PRIVATE jasmine_headers)
